### ISSUE TITLE
Button Color not displaying properly in front end  

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#161]
Testing ingot on 1.0.2 on Foundri.net test site. PHP 5. 6.16, WordPress 4.4.1- Theme twenty sixteen. Problem persist with all plugin deactivated 

![screen shot 2016-01-09 at 6 11 17 pm](https://cloud.githubusercontent.com/assets/14261015/12218916/6db3cd30-b6fc-11e5-8f2d-3c6e81f16a71.png)

**Comment by Shelob9** [comment]
Close via f911b11
