### ISSUE TITLE
In admin button color test sample do not look right. 

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#162]
Testing ingot v 1.0.2 on testing site foundri.net, PHP 5.6, Wordpress 4.4.1- Twenty Sixteen theme problem persist will all plugins deactivated 
![screen shot 2016-01-09 at 6 13 25 pm](https://cloud.githubusercontent.com/assets/14261015/12218927/17b018a2-b6fd-11e5-8f4c-2112844eb6b9.png)

**Comment by Shelob9** [comment]
37de88c fixes root problem, but it's not showing up for new buttons properly. Related #176 ?

**Comment by royboy789** [comment]
Looks like fixed in #176
