### ISSUE TITLE
Version checks only apply in the admin. #derphard

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#166]
Trying to test ingot 1.0.2 on the jpwp.me/ingot-test/ test site. Php version N/A. Wordpress 4.4.1. Theme N/A. Problem occurs when trying to visit the site. 

https://github.com/Ingothq/ingot/blob/master/ingot_bootstrap.php#L349

![screen shot 2016-01-10 at 8 33 38 pm](https://cloud.githubusercontent.com/assets/14261015/12225487/768869e2-b7d9-11e5-8472-68f12ba11c6d.png)

**Comment by Shelob9** [comment]
Test site was set to 5.3.29 which should have failed to load. Testing on Godaddy with PHP 5.4 did trip the bad PHP you shall not pass...

**Comment by Shelob9** [comment]
Could be that `PHP_VERSION` is not reliable...
