### ISSUE TITLE
Error continues to appear when trying to save the test group

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#188]
Testing Ingot V1.1.0 on foundri.net testing site, PHP 5.6.16, WordPress 4.4.1, Theme twenty sixteen, Problem persist when trying to save test group.
![screen shot 2016-01-18 at 10 27 37 pm](https://cloud.githubusercontent.com/assets/14261015/12408922/46a157f6-be33-11e5-9ee5-67593e45f0e9.png)

**Comment by Shelob9** [comment]
#176 Might have fixed this, need to check.

**Comment by Shelob9** [comment]
This was 1.1.0-b-1

**Comment by Shelob9** [comment]
Fixed in #176 #thanksroy
