### ISSUE TITLE
Variant names show as object not string in stats state

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#201]
Testing Ingot v.1.1.0-b-2 on testing site foundri.net, Php 5.6.28, Wordpress 4.4.1, theme twenty fifteen, identification is not be tracked when checking button states, each columns appears as ( Object, object)
problem is redundant. 
![screen shot 2016-01-20 at 5 43 34 pm](https://cloud.githubusercontent.com/assets/14261015/12465722/7ce17470-bf9d-11e5-9b0f-64e21b98e0b2.png)

**Comment by Shelob9** [comment]
Close via 0b9fd78
