### ISSUE TITLE
Variants not displaying properly when testing destination tests (Problem is consistent with other destination test) 

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#214]
Testing Ingot V1.1.0-b-3 on testing site Foundri.net, PHP 5.6.12, Wordpress 4.4.1, theme twenty fifteen, destination button not displaying correctly on screen ( error message appears) 
![screen shot 2016-01-23 at 3 29 38 pm](https://cloud.githubusercontent.com/assets/14261015/12532644/f3b0d280-c1e6-11e5-8421-087478935d7d.png)

**Comment by Shelob9** [comment]
Clsoe via d6d6a92

**Comment by Shelob9** [comment]
Root issue was #220 for the record
