### ISSUE TITLE
change one of the Woo options from cart into purchase  

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#215]
Testing ingot v1.1.0-b-3 on testing site foundri.net, PHP 5.6.12, WordPress 4.4.1, theme twenty fifteen, very small issue just needs to be changed on (destination type) 
![screen shot 2016-01-23 at 3 43 49 pm](https://cloud.githubusercontent.com/assets/14261015/12532700/27785ab0-c1e8-11e5-800e-2cd47582b4ae.png)

**Comment by Shelob9** [comment]
Good find @AndyLarre77 +2 points

**Comment by Shelob9** [comment]
Order is also bad http://i0.kym-cdn.com/entries/icons/original/000/000/246/copypasta.jpg

**Comment by Shelob9** [comment]
Close via 493cd3a
