### ISSUE TITLE
Settings dashboard has a code error. 

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#241]
Testing Ingot V.1.1.1-b-1 on testing site Foundri.net, PHP 5.6.16, WordPress V.4.4.2, twenty fifteen. error is displayed on screen 
![screen shot 2016-02-17 at 6 58 49 pm](https://cloud.githubusercontent.com/assets/14261015/13129189/3fc9e6cc-d5a9-11e5-9ecd-3876603c75e1.png)

**Comment by Shelob9** [comment]
`TypeError: $http(...).then(...).error is not a function`

**Comment by Shelob9** [comment]
close via 689a4bd
