### ISSUE TITLE
Skipping "Opt-In" leads to white screen

### ISSUE THREAD

**Issue by cgrymala** [Shelob9/ingot#255]
Not sure if this also happens when actually opting in, but when I first installed the plugin (on multisite), then activated it on the root site, then went to the Ingot page in the admin area of the root site, I was greeted by the screen asking me if I wanted to opt in to making the plugin better. I clicked the "Skip" button, and then the screen went white (fatal PHP error).

Looking at my server logs, the following error was output when this happened:

```
WordPress database error Duplicate column name 'wp_ID' for query ALTER TABLE oahkeq_ingot_group ADD COLUMN wp_ID VARCHAR(255) NOT NULL /* From [example.com/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=] in [/var/www/wp-content/plugins/ingot/vendor/ingot/ingot-core/classes/testing/db/upgrade.php:80] */ made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, ingot_bootstrap::maybe_load, ingot_bootstrap::maybe_upgrade, ingot\\testing\\db\\upgrade->run, ingot\\testing\\db\\upgrade->add_wp_id_column, referer: http://example.com/wp-admin/plugins.php
```

(replaced our actual domain with `example.com` in the error above)

I first noticed this error when installing the plugin on our production site, but was able to reliably reproduce it on our staging site, as well. We're running on WPEngine.

**Comment by cgrymala** [comment]
As a side note, it might have nothing to do with the error mentioned above; it might actually be because the admin URL is being built incorrectly after skipping the opt-in.

The URL that it redirects to is `/wp-admin/admin.php?ingot-admin-app` rather than `/wp-admin/admin.php?page=ingot-admin-app` (notice that `ingot-admin-app` is being used as the parameter name with no value, rather than `ingot-admin-app` being the value of the `page` parameter).

**Comment by Shelob9** [comment]
Optin white screen issue close via #ec3c6b8

The duplicate column warning is separate issue - #259
