### ISSUE TITLE
Freemius incompatibility

### ISSUE THREAD

**Issue by Shelob9** [Shelob9/ingot#265]
From Vova:
Got a note from developer that integrating FS that when he’s running his plugin in parallel to Ingot, there’s an error thrown. I done some research and realized that you have the following code:
```function ingot_maybe_load_premium( $type ){
    switch( $type ){
        case 'freemius' :
            if( 'premium' == ingot_fs()->get_plan() ){
                ingot_premium();
            }
            break;
        case 'edd' :
            //@todo
            break;
    }
}

```

And the reason it works well only with your plugin is because you modified the `get_plan` function. The thing is that when there’s another plugin that uses freemius with a newer SDK version, it will be automatically the active version. And that cause your code to fail. As I mentioned before, `get_plan()` should not be used.

A simple fix would be to change it to:
`if ( ingot_fs()->is_plan( 'premium' ) )`

@shelob9 Either make his fix or namespace the Freemius SDK or add a versioned loader like CMB2 does.
```

**Comment by vovafeldman** [comment]
If you don't want to have any future issues, it's better to "play by the best practices" and not modify the SDK code or its loading mechanism. To play safe, you should only use functions from `Freemius_Abstract`:
https://codedoc.pub/freemius/wordpress-sdk/master/class-Freemius_Abstract.html

**Comment by Shelob9** [comment]
close via           5fc10c4
