### ISSUE TITLE
Accepted Plugins Return

### ISSUE THREAD

**Issue by royboy789** [Shelob9/ingot#44]
Currently the return array gives a value of an integer, but the function for validating a plugin is based on a string. Suggest changing "value" of returned plugins to something like "edd" and "woo" and labels to be something like "Easy Digital Downloads" & "WooCommerce"

Creating a bypass in the Angular app for now where the value for the plugin select is actually the label. but this is #hacky

**Comment by royboy789** [comment]
confirming that changing the select's options' values to the label instead of value of each group.plugin has got it working.

**Comment by royboy789** [comment]
while you are at it.. you should really check for which plugin(s) are activated and return only those. if none, the select goes away and an error message stays in its place

**Comment by Shelob9** [comment]
Yah, I used the wrong function there. Value should be 'woo' or 'edd' that's what the PHPs expect.

**Comment by Shelob9** [comment]
a499d7c (and    a8f585c beacuse #gitfail) make it so not return the disabled plugins.

**Comment by Shelob9** [comment]
Closing as works now
