### ISSUE TITLE
UI: Price Group: Tests not sent back to API Properly

### ISSUE THREAD

**Issue by Shelob9** [Shelob9/ingot#58]
Screenshot of what payload looks like:

![screen shot 2015-11-18 at 6 13 20 pm](https://cloud.githubusercontent.com/assets/1994311/11257529/15b99146-8e20-11e5-87d9-3475bb3b1ac7.png)

**Comment by royboy789** [comment]
Trying to save the random identifier as a string instead of an integer, but when random ID is created it is an integer so array[1002], which means array[0] - array[1001] need to exist, even if NULL

**Comment by Shelob9** [comment]
@royboy789 IF the problem is that the random string we're assigning as ID, so `if ( 0 == absint( $id ) )` will evaluate true and cause new test to be created from data, why don't we assign ID as 0 for new tests?

Only issue I see is that I was using test ID to form HTML attribute ID, and having to attributes with same ID is invalid HTML. Easy ways around that secondary issue.

**Comment by Shelob9** [comment]
Fixed via all them commits
