### ISSUE TITLE
Stats: make work with new CRUD

### ISSUE THREAD

**Issue by Shelob9** [Shelob9/ingot#88]
Since sequences are no longer a thing, graphs should be one big bar graph with

1) Group conversion rate
2) Conversion rate for each varient

New CRUD defined in #81 

Wait until changes in API are documented

**Comment by royboy789** [comment]
2) Variant IDs are meaningless.
3) A direct link to editing current group would be cool.

**Comment by royboy789** [comment]
2) Variant IDs are meaningless. - waiting on @Shelob9 to make it easily possible.

**Comment by Shelob9** [comment]
@royboy789 fc70f47 gives you the group/variant names in the /stats response.

Moving to the 1.0 milestone in hopes you can come up with solution for X axis label if is button_color_test issue.
