### ISSUE TITLE
Before choosing step in new/edit click group ng-includes tries and fails to load a partial

### ISSUE THREAD

**Issue by Shelob9** [Shelob9/ingot#93]
`http://ingot-dev.dev/wp-content/plugins/ingot/assets/admin/partials//content-test-partials/.html` is GETed. 403 occurs.

**Comment by Shelob9** [comment]
71ef09c fixes this in new state, but not in edit state. Grrr argh.

**Comment by royboy789** [comment]
fixed in b7910173cd04d9429d5e5a3f32c7292908f28f20
